### ISSUE TITLE
New TasmoAdmin release

### ISSUE THREAD

**Issue by EPMatt** [TasmoAdmin/TasmoAdmin#465] opened 2022-02-26 18:22 UTC
Hi there,

first of all, I'd like to show my deep appreciation for this useful web application. TasmoAdmin makes managing multiple Tasmota devices a breeze. Thank you for maintaining and developing such a cool project! 🚀 

I can see a few features and fixes have been introduced since the last release more than one year ago. Most notably, GZip support was implemented last November (#447). However, users of the [Home Assistant addon](https://github.com/hassio-addons/addon-tasmoadmin) cannot benefit from these features, since the addon points to the latest "official" release, `v1.7.0`, which dates back to September 2020.

Will a new version of TasmoAdmin be released here on GitHub at some point in the future? Publishing a new version would allow many more people, including users of the Home Assistant Addon, to update TasmoAdmin and use the new features.

Thank you so much for your time!

**Comment by inverse** [comment] 2022-02-26 21:18
Hi!

Thanks for raising this! 

I have some rights on this repository but I am unable to set the secrets required in #452  which as I understand is the blocker for for releasing to Dockerhub as the Travis way was broken (@reloxx13 correct me if I am wrong).

What could be done to mitigate this is to create the HA Addon from a commit hash which would get the gzip gains but I am not sure how well that would be recieved in that ecosystem using non-tagged releases.

**Comment by inverse** [comment] 2022-02-26 21:55
@reloxx13 looks like that side of things is blocking a new release.

**Comment by inverse** [comment] 2022-02-27 20:51
@EPMatt exactly 


I hope that the main developer comes back to we can unblock this and push a new release out as I can imagine its quite annoying for users going forward.

**Comment by reloxx13** [comment] 2022-02-27 20:56
hey guys, what do you need? i created those secrets and they should be available as placeholder

**Comment by inverse** [comment] 2022-02-27 21:12
Nothing else needed from your side (unless you want too) What's needed is:

- New release tagged on the repo
- HA addon to be bumped for that (that should be fairly straight forward)

**Comment by inverse** [comment] 2022-02-27 21:40
@reloxx13 what would you tag this with? Looking at the release notes I'm not sure if this project follows semantic versioning but I would go with `v.1.8.0` with this due to the addition of gzip support.

**Comment by reloxx13** [comment] 2022-02-27 21:48
> v1.8.0

Is fine for me

Thanks again everyone for your great effort! I lost hope with broken travis.

**Comment by inverse** [comment] 2022-02-27 22:01
The CI needs to be improved but can do that another time. I tagged the release and the build is kicking off.

https://github.com/reloxx13/TasmoAdmin/runs/5352646673?check_suite_focus=true (failed due to dockerhub credential issues it seems) 

We should be unblocked for Home Assistant though.

**Comment by inverse** [comment] 2022-02-27 22:04
HA side PRd

- https://github.com/hassio-addons/addon-tasmoadmin/pull/230
- https://github.com/hassio-addons/addon-tasmoadmin/pull/231

**Comment by inverse** [comment] 2022-02-28 19:55
Both pull requests merged - waiting for them to release 🚀

**Comment by EPMatt** [comment] 2022-03-01 13:54
Hi there,

thank you all for looking into this! 🚀 Should we close this ticket? I think everything that was requested on TasmoAdmin's side to address this issue has been carried out successfully. 👍🏻 

Thanks again!

**Comment by mprins** [comment] 2022-03-01 16:49
well, we're still waiting for the docker image to be published

**Comment by inverse** [comment] 2022-03-01 17:54
@reloxx13 are you able to check if the dockerhub credentials are correct? 

https://github.com/reloxx13/TasmoAdmin/runs/5352646673?check_suite_focus=true - it looks like things blew up when publishing.


I manually fixed the issue with artifacts not being included on the release due to this failing which I believe caused #470

**Comment by reloxx13** [comment] 2022-03-01 18:37
the credentials where saved in travis by @RaymondMouthaan docherhub account. i dont think he will add it in this repo now as secret as i could be able to see it. we may use our own docker hub account now. raymonds account was also hitting the free limit of dockerhub.

**Comment by inverse** [comment] 2022-03-01 19:56
The secrets that @RaymondMouthaan should be able to be recreated but he would be the one to have to do that. 

Lets hope he can otherwise it would require transferring to a new account. 

Thanks for the reply 🙏🏼

**Comment by inverse** [comment] 2022-03-23 21:46
@mprins  We migrated from Docker Hub to GitHub packages to provide a better way to manage things.

The images are available at: https://github.com/orgs/TasmoAdmin/packages/container/package/tasmoadmin

**Closed** 2022-03-23 21:46 UTC
Labels: HOT

**Comment by jk-andersen** [comment] 2022-03-24 07:22
This is a 404?

**Comment by inverse** [comment] 2022-03-24 07:39
@reloxx13  can you make the package visitability public? I can't do it.


You should be able to pull with docker pull ghcr.io/tasmoadmin/tasmoadmin:v1.8.0

**Comment by inverse** [comment] 2022-03-24 07:57
@reloxx13  can you make the package visitability public? I can't do it.


You should be able to pull with docker pull ghcr.io/tasmoadmin/tasmoadmin:v1.8.0

**Comment by reloxx13** [comment] 2022-03-24 08:18
> @reloxx13 can you make the package visitability public? I can't do it.
> 
> @jk-andersen
> 
> You should be able to pull with docker pull ghcr.io/tasmoadmin/tasmoadmin:v1.8.0

Heya,

i cannot do this neither, its grayed out

![grafik](https://user-images.githubusercontent.com/14855001/159872408-128b7062-a874-4d5f-9100-4d9b04ff0a91.png)

**Comment by jk-andersen** [comment] 2022-03-24 08:20
@inverse - No.
Error response from daemon: Head "https://ghcr.io/v2/tasmoadmin/tasmoadmin/manifests/v1.8.0": unauthorized

**Comment by reloxx13** [comment] 2022-03-24 08:24
> @reloxx13 can you make the package visitability public? I can't do it.

Heya,
The package is now public.

**Comment by inverse** [comment] 2022-03-24 08:27
@jk-andersen what about with the change to make it public?

Thanks @reloxx13

**Comment by mprins** [comment] 2022-03-24 08:40
thanks!
I can confirm that it is now possible to `docker pull ghcr.io/tasmoadmin/tasmoadmin` and  `docker pull ghcr.io/tasmoadmin/tasmoadmin:v1.8.0` succesfully

**Comment by EPMatt** [comment] 2022-04-22 09:59
Hi @inverse @reloxx13,

sorry for my late answer, but I just wanted to thank you for looking into this issue. I'm happy to see that a new version was published for the HA addon as well! :)

Thank you so much for your precious time! 🚀
