### ISSUE TITLE
Automatic Updates Fail - Could not download firmware from GITHUB!

### ISSUE THREAD

**Issue by broyuken** [TasmoAdmin/TasmoAdmin#427] opened 2021-01-19 20:33 UTC
Looks like the issue from #395 has popped up again. I get the same error when trying to update automatically OTA. I wasn't even able to update it via downloading the binary and uploading it. 

Using the HA addon version 0.13.1

When uploading file manually. It says update done, but the update is not done. This used to work previously.
` [19-01-2021 15:33:24][GLOBAL] Start update process[19-01-2021 15:33:24][ID-3][STEP-2][GLOBAL] Start Step 2[19-01-2021 15:33:24][ID-3][STEP-2][CHECK] Check Connection | TRY => 1[19-01-2021 15:33:24][ID-1][STEP-2][GLOBAL] Start Step 2[19-01-2021 15:33:24][ID-1][STEP-2][CHECK] Check Connection | TRY => 1[19-01-2021 15:33:24][ID-2][STEP-2][GLOBAL] Start Step 2[19-01-2021 15:33:24][ID-2][STEP-2][CHECK] Check Connection | TRY => 1[19-01-2021 15:33:24][ID-1][STEP-2][CHECK] Connection Successfully! | Current Version => 9.1.0(tasmota)[19-01-2021 15:33:24][ID-1][STEP-2][OTAURL] Set OTA URL for Firmware => NEW FW[19-01-2021 15:33:24][ID-1][STEP-2][OTAURL] OTA Url => http://ha.broyuken.com:9541/data/firmwares/tasmota.bin[19-01-2021 15:33:24][ID-2][STEP-2][CHECK] Connection Successfully! | Current Version => 9.1.0(tasmota)[19-01-2021 15:33:24][ID-2][STEP-2][OTAURL] Set OTA URL for Firmware => NEW FW[19-01-2021 15:33:24][ID-2][STEP-2][OTAURL] OTA Url => http://ha.broyuken.com:9541/data/firmwares/tasmota.bin[19-01-2021 15:33:24][ID-3][STEP-2][CHECK] Connection Successfully! | Current Version => 9.1.0(tasmota)[19-01-2021 15:33:24][ID-3][STEP-2][OTAURL] Set OTA URL for Firmware => NEW FW[19-01-2021 15:33:24][ID-3][STEP-2][OTAURL] OTA Url => http://ha.broyuken.com:9541/data/firmwares/tasmota.bin[19-01-2021 15:33:24][ID-1][STEP-1][OTAURL] OTA URL set for Firmware => NEW FW[19-01-2021 15:33:24][ID-1][STEP-2][UPDATE] Trigger device update...[19-01-2021 15:33:24][ID-2][STEP-1][OTAURL] OTA URL set for Firmware => NEW FW[19-01-2021 15:33:24][ID-2][STEP-2][UPDATE] Trigger device update...[19-01-2021 15:33:24][ID-2][STEP-2][UPDATE] Device update triggered[19-01-2021 15:33:24][ID-2][STEP-2][CHECK UPDATE] Wait for update | Seconds => 60[19-01-2021 15:33:24][ID-3][STEP-1][OTAURL] OTA URL set for Firmware => NEW FW[19-01-2021 15:33:24][ID-3][STEP-2][UPDATE] Trigger device update...[19-01-2021 15:33:24][ID-1][STEP-2][UPDATE] Device update triggered[19-01-2021 15:33:24][ID-1][STEP-2][CHECK UPDATE] Wait for update | Seconds => 60[19-01-2021 15:33:24][ID-3][STEP-2][UPDATE] Device update triggered[19-01-2021 15:33:24][ID-3][STEP-2][CHECK UPDATE] Wait for update | Seconds => 60[19-01-2021 15:34:24][ID-2][STEP-2][DONE] ============= Update done! =============[19-01-2021 15:34:24][ID-1][STEP-2][DONE] ============= Update done! =============[19-01-2021 15:34:24][ID-3][STEP-2][DONE] ============= Update done! =============`

When selecting automatic update I get the following errors on the screen before I click "Start Update"

Notice: Undefined property: stdClass::$assets in /var/www/tasmoadmin/tasmoadmin/pages/upload.php on line 176

Warning: Invalid argument supplied for foreach() in /var/www/tasmoadmin/tasmoadmin/pages/upload.php on line 176

**Comment by rafuz** [comment] 2021-04-25 07:59
same problem here, using home assistan plugin 0.15

**Comment by arendst** [comment] 2021-04-25 08:14
As the binaries are no longer attached to the release it's time tasmoadmin moves to using the ota.tasmota.com site for released binaries

**Comment by gerhardheim** [comment] 2021-05-04 07:36
Hi,
I inserted following lines in the file upload.php on line 185:
```
                                $fwMinimalUrl = "http://ota.tasmota.com/tasmota/release/tasmota-minimal.bin";
                                $fwUrl = "http://ota.tasmota.com/tasmota/release/".$fwAsset;
```
now it works for me

**Comment by spider7611** [comment] 2021-05-04 08:16
Ok, but where can I find this upload.php file?

**Comment by gerhardheim** [comment] 2021-05-04 08:35
> Ok, but where can I find this upload.php file?

/var/www/tasmoadmin/pages/upload.php

**Comment by spider7611** [comment] 2021-05-04 08:57
Ok, I have this on line 185:

`if (isset($fwUrl) && isset($fwMinimalUrl)) { `

**Comment by gerhardheim** [comment] 2021-05-04 09:24
> Ok, I have this on line 185:
> 
> `if (isset($fwUrl) && isset($fwMinimalUrl)) { `

Before that I inserted the lines mentioned above. 
But I did no testing with different settings. Just i said: It worked for me. Maybe you give the code a close look and than you can see that it is a quick and dirty solution that will probably crash if something else will be changed. So if you are not sure or you don't know what it does, please don't use it. I'm not responsible for anything!

**Comment by spider7611** [comment] 2021-05-04 09:26
Ok, thank You!

**Comment by CodeFinder2** [comment] 2021-05-08 13:06
> Hi,
> I inserted following lines in the file upload.php on line 185:
> 
> ```
>                                 $fwMinimalUrl = "http://ota.tasmota.com/tasmota/release/tasmota-minimal.bin";
>                                 $fwUrl = "http://ota.tasmota.com/tasmota/release/".$fwAsset;
> ```
> 
> now it works for me

Why not making a PR?

**Comment by gerhardheim** [comment] 2021-05-10 06:14
> > Hi,
> > I inserted following lines in the file upload.php on line 185:
> > ```
> >                                 $fwMinimalUrl = "http://ota.tasmota.com/tasmota/release/tasmota-minimal.bin";
> >                                 $fwUrl = "http://ota.tasmota.com/tasmota/release/".$fwAsset;
> > ```
> > 
> > 
> > now it works for me
> 
> Why not making a PR?
Please feel free to do so

**Comment by MrFloppy** [comment] 2021-05-19 11:36
The issue is triggererd by the fact, that tasmota is not appending all of the binaries they create to the latest release. Only two archives are present. Maybe this will solve itself, as soon as the next version is released and they return to the old way of adding binaries.

See asset page of 9.3.1: https://api.github.com/repos/arendst/Tasmota/releases/38481601
vs
See asset page of 9.4.0: https://api.github.com/repos/arendst/Tasmota/releases/41894033

**Comment by liamrpowell** [comment] 2021-06-11 02:12
> Hi,
> I inserted following lines in the file upload.php on line 185:
> 
> ```
>                                 $fwMinimalUrl = "http://ota.tasmota.com/tasmota/release/tasmota-minimal.bin";
>                                 $fwUrl = "http://ota.tasmota.com/tasmota/release/".$fwAsset;
> ```
> 
> now it works for me

Where would I find this file in Home assistant? Anyone know?

Thank you,

**Comment by user45876** [comment] 2021-06-15 12:43
Thanks to all for confirming and giving a fix. I can confirm that this issue still exists and that the fix is working. Unfortunately I am using docker and would have to do the fix anytime, I restart the container, unless I would rebuild the image.

Wrapping it up:
- edit /var/www/tasmoadmin/pages/upload.php
- insert this `$fwMinimalUrl = "http://ota.tasmota.com/tasmota/release/tasmota-minimal.bin";$fwUrl = "http://ota.tasmota.com/tasmota/release/".$fwAsset;` BEFORE line 185 `if (isset($fwUrl) && isset($fwMinimalUrl)) {`

**Comment by baldfox** [comment] 2023-04-18 14:18
I mean it's still not working for me. Whenever I try to autoupdate it just times out as has been mentioned above.

**Comment by CodeFinder2** [comment] 2023-04-18 14:20
Dito

**Comment by inverse** [comment] 2023-04-18 19:53
@baldfox & @CodeFinder2 can you describe your issue in more detail the original issue is 2 years old and a lot has changed since then.

What version of TasmoAdmin are you running?

**Comment by CodeFinder2** [comment] 2023-04-21 19:43
@inverse sorry for the late reply and thanks for taking a look!

I am running this as an addon on Home Assistant 2023.4.5 (supervised) on a Raspberry Pi 4B (64 bit Rasbian).The [addon](https://github.com/hassio-addons/addon-tasmoadmin) has v0.24.1 which is using the latest version of TasmoAdmin v3.0.2.

TasmoAdmin correctly lists my 2 devices. When I switch to the "Update" section, press the "Autonomic" button, select a device and start the update, it says:
```
Unable to access OTA URL @ http://172.30.33.1:9541/data/firmwares/tasmota-DE.bin.gz - TypeError: Failed to fetch 
```
Frontend and Backend checks are enabled in the settings.

Please let me know if you need further information! 😊

**Comment by CodeFinder2** [comment] 2023-04-24 08:27
@user45876 thanks for the hint. Seems to have helped:
```
2023-04-24T08:25:10.961Z] Starte Update Prozess
[2023-04-24T08:25:10.961Z] Attempting upgrade to version 12.5.0
[2023-04-24T08:25:10.962Z] Checking version...
[2023-04-24T08:25:11.315Z] Current version is 12.5.0(tasmota)
[2023-04-24T08:25:11.316Z] Device already at target version 
```
Will test again and report back if there's a new version for Tasmota available (already up-to-date). 😄

**Comment by toxicfirefly** [comment] 2023-06-11 06:13
I ran into this issue today. The `172.*.*.*` address in the TasmotaAdmin is the internal Docker IP address. Once I changed the `172.*.*.*` address to the IP of my Home Assistant server, I was able to click the `Automatic` button to update my devices.

**Comment by inverse** [comment] 2023-06-11 19:14
@user45876 interesting - are you able to access the firmware on the URL through your browser?

**Comment by JMVS** [comment] 2023-07-09 22:58
> Good to hear :) Unfortunately, this does not help in my case, as it is a different problem. I have the IP set to the one of my HA but I am getting the error, as described above, when clicking 'Automatik'. It does not seem to try or start downloading.
> 
> ```
> Full Firmware is not accessible on the server at http://192.168.128.235:9541/data/firmwares/tasmota.bin.gz
> Please check the OTA IP address and port are correct
> ```



> @user45876 interesting - are you able to access the firmware on the URL through your browser?

Hello. I'm having the same problem with HA. It seems to be related to the fact that TasmaAdmin tries to access the IP via http but it really should be http**s** thus failing.

**Comment by Razer0123** [comment] 2023-08-01 05:22
> > Good to hear :) Unfortunately, this does not help in my case, as it is a different problem. I have the IP set to the one of my HA but I am getting the error, as described above, when clicking 'Automatik'. It does not seem to try or start downloading.
> > ```
> > Full Firmware is not accessible on the server at http://192.168.128.235:9541/data/firmwares/tasmota.bin.gz
> > Please check the OTA IP address and port are correct
> > ```
> 
> > @user45876 interesting - are you able to access the firmware on the URL through your browser?
> 
> Hello. I'm having the same problem with HA. It seems to be related to the fact that TasmaAdmin tries to access the IP via http but it really should be http**s** thus failing.

Yes i can confirm this is totally the issue, could anyone fix it please?

**Comment by JMVS** [comment] 2023-09-30 17:25
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
> 
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

Yes, it is still relevant. Still need to update http to https

**Comment by inverse** [comment] 2023-11-02 21:17
@JMVS it sounds like your issue is unrelated to the original. Will close this since it's very old and out of date. Please create a new issue with the problem you're facing.

**Closed by inverse** 2023-11-02 21:17 UTC
Labels: bug

**Comment by smoldersonline** [comment] 2023-12-21 06:44
+1 for me. Still not working.

I'm not 100%, but also think an update from http to https is required.

Thank you!

`Minimal Firmware is not accessible on the server at http://xxx.xxx.xxx.xx:9541/data/firmwares/tasmota-minimal.bin.gz
Please check the OTA IP address and port are correct
Full Firmware is not accessible on the server at http://xxx.xxx.xxx.xx:9541/data/firmwares/tasmota.bin.gz
Please check the OTA IP address and port are correct`

**Comment by inverse** [comment] 2023-12-21 10:28
Please create a new issue outlining your problem
