### ISSUE TITLE
MQTT Password not set correctly on device when ending in `;`

### ISSUE THREAD

**Issue by hostirosti** [TasmoAdmin/TasmoAdmin#425] opened 2021-01-03 04:15 UTC
If the MQTTPassword set in the Device Config is ending with `;` that char is omitted when sent to the device.

**Comment by inverse** [comment] 2022-05-29 20:13
Closing as dupe of https://github.com/TasmoAdmin/TasmoAdmin/issues/424

**Closed by inverse** 2022-05-29 20:13 UTC
