### ISSUE TITLE
Selfupdate error: Could not find any Download Release (Travis Fail?)

### ISSUE THREAD

**Issue by flane71** [TasmoAdmin/TasmoAdmin#485] opened 2022-04-02 07:12 UTC
I have Tasmoadmin v1.7.0 (Raspberry Pi with Buster), and have this error with Tasmoadmin Selfupdate page:

_Could not find any Download Release (Travis Fail?)
Please check your internet connection_

![Cattura](https://user-images.githubusercontent.com/77128022/161371516-bce639d3-ea27-463b-8de1-a64772b1297c.PNG)

My internet connection is working fine.
Version 1.8.0 is currently available
How can I solve?
Thanks

**Comment by kirichkov** [comment] 2022-04-03 11:10
The repository has been renamed, but even the latest version references the old repository URL. To fix it  you must manually change [`includes/Selfupdate.php`](https://github.com/TasmoAdmin/TasmoAdmin/blob/d335bffa0b372623a52731d2ee83822d3a130ebd/tasmoadmin/includes/Selfupdate.php#L6) Line 6 to reference the new URL:


```php
	private $repoUrl    = "https://api.github.com/repos/TasmoAdmin/TasmoAdmin";
```

**Comment by inverse** [comment] 2022-04-03 14:49
Ouch yeah this was an oversight on us when migrating the repository to an organisation - I created a pull request to resolve this going forward but unfortunately will be problematic until the next release lands.

**Comment by jolu1705** [comment] 2022-05-01 06:56
I have changed the repo url like stated but this does not solve the issue for me. Any other idea?

**Comment by mcmellow** [comment] 2022-05-20 09:32
> The repository has been renamed, but even the latest version references the old repository URL. To fix it you must manually change [`includes/Selfupdate.php`](https://github.com/TasmoAdmin/TasmoAdmin/blob/d335bffa0b372623a52731d2ee83822d3a130ebd/tasmoadmin/includes/Selfupdate.php#L6) Line 6 to reference the new URL:
> 
> ```
> 	private $repoUrl    = "https://api.github.com/repos/TasmoAdmin/TasmoAdmin";
> ```

I have changed this line and forced an update by clicking on the Start SelfUpdate button. The update went OK.
However the line with private $repoUr was changed during the update to the previous value

`
private $repoUrl    = "https://api.github.com/repos/reloxx13/TasmoAdmin";
`
So next update will go wrong again.

**Comment by inverse** [comment] 2022-05-20 09:42
@mcmellow the next release has this properly fixed through renaming the URL (check out master) as well as following redirects for future changes. However the next update also brings some breaking changes in the form of:

- Setting minimum PHP version to 7.4
- Adopting composer for dependencies

**Comment by mcmellow** [comment] 2022-05-20 10:55
@inverse Thanks for your update.
PHP Version 7.3.31-1 deb10u1.  But after an update I have PHP v7.4 and  v8.1 on my Raspberry 3b+ 
However according info.php TasmoAdmin is still using  PHP Version 7.3.31-1 deb10u1  
How do I change this and wich PHP version.

**Comment by inverse** [comment] 2022-05-20 14:25
@mcmellow How did you do the upgrade and what is your webserver stack? 

I suspect you need to restart your web server (and php-fpm if you're using php with that)

**Comment by mcmellow** [comment] 2022-05-20 15:08
@inverse 
I did not work out quit well. So I removed to complete /var/www/tasmoadmin folder with all its contents.
Reinstalled it as described in [the Tasmota documents](https://tasmota.github.io/docs/TasmoAdmin/). 
Faced some wrong source links (this page need some updates) I use apache2
At the first atrt I received these errors
`
Warning: require_once(/var/www/tasmoadmin/tasmoadmin/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/tasmoadmin/tasmoadmin/includes/bootstrap.php on line 103

Fatal error: require_once(): Failed opening required '/var/www/tasmoadmin/tasmoadmin/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/tasmoadmin/tasmoadmin/includes/bootstrap.php on line 103

`
I used this source link https://github.com/TasmoAdmin/TasmoAdmin.git  There is no folder  tasmoadmin/vendors ion my RPi after the git clone

**Comment by inverse** [comment] 2022-05-20 16:00
@mcmellow  Ouch that documentation is out of date - will need to find a way to sync the current documentation.


Best bet is to use one of the zip files packaged on the releases: https://github.com/TasmoAdmin/TasmoAdmin/releases/download/v1.8.0/tasmoadmin_v1.8.0.zip

or if you're feeling adventurous  you could try the latest beta release... it comes with the composer dependencies already baked in. https://github.com/TasmoAdmin/TasmoAdmin/releases/download/v2.0.0-beta2/tasmoadmin_v2.0.0-beta2.zip

**Comment by mcmellow** [comment] 2022-05-20 17:20
@inverse  Thanks for your answer.

Made a dowload of tasmoadmin_v18.0.zip.   The link in includes/Selfupdate.php is still the wrong link to ../repos/reloxx13/..
I was able to scan all my Tasmota devices correctly. 
Made an update to v20.0-beta2  by selfupdate. It looks OK but received the following error

`
Warning: copy(/var/www/tasmoadmin/tasmoadmin//resources/css/bootstrap/bootstrap-grid.css.map): failed to open stream: Permission denied in /var/www/tasmoadmin/tasmoadmin/src/SelfUpdate.php on line 281
`
There is a double slash / between tasmoadmin and resources  But I am not sure or this is the cause op this error. 
Another annoying point. The selfupdate error line mesh up the other screens like start and device list.  Clearing the browsercache does help.

**Comment by inverse** [comment] 2022-05-20 19:16
@mcmellow interesting - nothing much changed to that file since v1.8.0 - I didn't have a chance to look into that code much since helping more on the project

**Comment by mcmellow** [comment] 2022-05-21 10:09
> @mcmellow interesting - nothing much changed to that file since v1.8.0 - I didn't have a chance to look into that code much since helping more on the project

Another annoying point. The selfupdate error messages mesh up the other screens like start and device list. Clearing the browsercache does not help to clear the error messages. 

This happend after the update to 2.0.0-beta2.  Any hint how I can get remove these error messages

**Comment by inverse** [comment] 2022-05-21 10:26
@mcmellow can you provide a screenshot? I've not tried the self update logic before as I normally run things via docker... will need to investigate time permitting.

**Comment by mcmellow** [comment] 2022-05-22 10:56
![image](https://user-images.githubusercontent.com/15740537/169691763-7166415c-d327-4496-90c7-1b4964b619d5.png)
This is the start screen, but it is also on the devices-list

**Comment by inverse** [comment] 2022-05-22 19:27
@mcmellow okays - thats something blowing up - I should be able to fix that and push a new beta release for you to migrate too...

**Comment by inverse** [comment] 2022-05-22 19:36
this should fix it https://github.com/TasmoAdmin/TasmoAdmin/pull/537

**Comment by inverse** [comment] 2022-05-22 19:58
@mcmellow just published this https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.0.0-beta3

You should be able to update to it shortly once the artifacts are built...

![image](https://user-images.githubusercontent.com/713525/169713534-9a9c09e1-fd6c-4e36-8ab3-7e344b4858fc.png)


You should be able to change the update channel in the settings to BETA to be able to update via the update process to these.

**Comment by mcmellow** [comment] 2022-05-24 19:38
@inverse  Thanks for the update. It work partial. The start screen is OK now. The devices list is still a mesh. See picture below.
![TasmoadminError](https://user-images.githubusercontent.com/15740537/170118278-3c8dd27f-9e50-4b90-ab44-2ecce7f3b055.png)

**Comment by inverse** [comment] 2022-05-24 21:48
@mcmellow that should fix it https://github.com/TasmoAdmin/TasmoAdmin/pull/538

**Comment by jolu1705** [comment] 2022-05-25 05:57
So I have downloaded beta4 and copied all files over my v1.7 installation but no matter what I do, it shows me version 1.7 and SelfUpdate is not working even with the changed URL in /includes/Selfupdate.php

Can anyone assist please?

**Comment by inverse** [comment] 2022-05-25 19:59
@mcmellow this should fix that https://github.com/TasmoAdmin/TasmoAdmin/pull/540

New release being built.

**Comment by inverse** [comment] 2022-05-25 20:27
@jolu1705 what is your setup? Sounds strange that its not reflecting the update

**Comment by jolu1705** [comment] 2022-05-27 06:02
> @jolu1705 what is your setup? Sounds strange that its not reflecting the update

Linux optiplex7050 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

**Comment by inverse** [comment] 2022-08-15 21:07
Closing as we are a few versions beyond so shouldn't happen again

**Closed by inverse** 2022-08-15 21:07 UTC
