### ISSUE TITLE
Page /upload_form issuse

### ISSUE THREAD

**Issue by kfulko** [TasmoAdmin/TasmoAdmin#658] opened 2022-09-08 20:20 UTC
Error when click a upload_form page to update Tasmota devices.

Actual error on page:
`Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: SSL connection timeout (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://raw.githubusercontent.com/arendst/Tasmota/development/RELEASENOTES.md?r=1662312596 in /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210 Stack trace: #0 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection() https://github.com/hassio-addons/addon-tasmoadmin/issues/1 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError() https://github.com/hassio-addons/addon-tasmoadmin/issues/2 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish() https://github.com/hassio-addons/addon-tasmoadmin/issues/3 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke() https://github.com/hassio-addons/addon-tasmoadmin/issues/4 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler{closure}() https://github.com/hassio-addons/addon-tasmoadmin/issues/5 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler{closure}() https://github.com/hassio-addons/addon-tasmoadmin/issues/6 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke() https://github.com/hassio-addons/addon-tasmoadmin/issues/7 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp{closure}() https://github.com/hassio-addons/addon-tasmoadmin/pull/8 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke() https://github.com/hassio-addons/addon-tasmoadmin/issues/9 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp{closure}() https://github.com/hassio-addons/addon-tasmoadmin/issues/10 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke() https://github.com/hassio-addons/addon-tasmoadmin/issues/11 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer() https://github.com/hassio-addons/addon-tasmoadmin/issues/12 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync() https://github.com/hassio-addons/addon-tasmoadmin/issues/13 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request() https://github.com/hassio-addons/addon-tasmoadmin/issues/14 /var/www/tasmoadmin/tasmoadmin/src/Helper/TasmotaHelper.php(26): GuzzleHttp\Client->get() https://github.com/hassio-addons/addon-tasmoadmin/issues/15 /var/www/tasmoadmin/tasmoadmin/pages/upload_form.php(7): TasmoAdmin\Helper\TasmotaHelper->getReleaseNotes() https://github.com/hassio-addons/addon-tasmoadmin/issues/16 /var/www/tasmoadmin/tasmoadmin/index.php(55): include_once('...') https://github.com/hassio-addons/addon-tasmoadmin/issues/17 {main} thrown in /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210
`
Addon version: 2.00
Home Assistant Version: 2022.08.3
Supervisor Version: 2022.08.5

Another webpage on this addon works, addon have many restart, addon don't have any errors on log page.
![188326615-5c21c16d-6fc8-45e8-8698-391b9cbeddc4](https://user-images.githubusercontent.com/3510639/189217017-0a4774e0-ab27-454a-81b3-4a74ab443874.png)

**Comment by inverse** [comment] 2022-09-08 20:48
It's caused by the addon not being able to connect to GitHub to download the release notes.

It shouldnt blow up like this and should be fixed in the next version.

**Comment by inverse** [comment] 2022-10-06 19:58
New version published https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.1.0

**Closed by inverse** 2022-10-06 19:58 UTC
Labels: BUG
