### ISSUE TITLE
Problem loading Device Details and Selfupdate says no Network

### ISSUE THREAD

**Issue by ymurawski** [TasmoAdmin/TasmoAdmin#489] opened 2022-04-10 02:49 UTC
Hi, i just installed Tasmoadmin mit php8.0 and i have a strange behavior.
In the device list, it doenst load any detail. In the start page it shows the right power on state.

And if i go to the Self update Tab, it always says no network ?
But my network is working fine.

Any advice ?
![Screenshot 2022-04-10 044836](https://user-images.githubusercontent.com/46036625/162599087-7047a738-11a8-4fd3-b445-80ec082c2a11.png)
![Screenshot 2022-04-10 044904](https://user-images.githubusercontent.com/46036625/162599088-c2750cfb-bafe-41c8-a4fa-7c0d2b337904.png)
![Screenshot 2022-04-10 044920](https://user-images.githubusercontent.com/46036625/162599089-62618e9a-4e9e-442a-9282-0d2e5952d01f.png)

**Comment by inverse** [comment] 2022-04-11 07:27
How did you install? Was it bis the releases page or using a direct download? 

I'm unable to reproduce your issue  - did this ever work for you?

There is an issue with the current release regarding self update due to moving the repo under an organisation account. This will be resolved in the next release.

**Comment by ymurawski** [comment] 2022-04-11 07:45
> How did you install? Was it bis the releases page or using a direct download?
> 
> I'm unable to reproduce your issue - did this ever work for you?
> 
> There is an issue with the current release regarding self update due to moving the repo under an organisation account. This will be resolved in the next release.

I used the install instructions here for Ubuntu but just with PHP 8.0 because the instruction is really outdated 😅


I used this instructions on an old system and there it worked perfect. 
I would use it as a docker but in docker there is no option for Self Update.

**Comment by inverse** [comment] 2022-04-11 07:54
> I used the install instructions here for Ubuntu but just with PHP 8.0 because the instruction is really outdated sweat_smile

Yeah they are super old. We should really include some test harness with Vagrant and the alike to make testing this setup easier.


> I would use it as a docker but in docker there is no option for Self Update.

Isn't that just a case of running `pull` against the latest and starting again? Or updating the pinned version?

**Comment by ymurawski** [comment] 2022-04-11 10:31
> > I used the install instructions here for Ubuntu but just with PHP 8.0 because the instruction is really outdated sweat_smile
> 
> Yeah they are super old. We should really include some test harness with Vagrant and the alike to make testing this setup easier.
> 
> > I would use it as a docker but in docker there is no option for Self Update.
> 
> Isn't that just a case of running `pull` against the latest and starting again? Or updating the pinned version?

I did the under Ubunti via "docker run -it -v /host/data:/data -p 9999:80 --name tasmoadmin raymondmm/tasmoadmin"
There is version 1.7 and no Tab Self Update.

An easy install sript like for PiHole or IoBroker would be so awesome.

**Comment by inverse** [comment] 2022-04-11 12:25
> I did the under Ubunti via "docker run -it -v /host/data:/data -p 9999:80 --name tasmoadmin raymondmm/tasmoadmin"

Unfortunately we lost access to that docker hub account and migrated to using GitHub's container registry

e.g.

```bash
docker run -it -v /host/data:/data -p 9999:80 --name tasmoadmin ghcr.io/tasmoadmin/tasmoadmin:latest
```

**Comment by ymurawski** [comment] 2022-04-11 12:31
> > I did the under Ubunti via "docker run -it -v /host/data:/data -p 9999:80 --name tasmoadmin raymondmm/tasmoadmin"
> 
> Unfortunately we lost access to that docker hub account and migrated to using GitHub's container registry
> 
> e.g.
> 
> ```shell
> docker run -it -v /host/data:/data -p 9999:80 --name tasmoadmin ghcr.io/tasmoadmin/tasmoadmin:latest
> ```
> 
> > An easy install sript like for PiHole or IoBroker would be so awesome.
> 
> I think using a docker based solution would be the best way to handle this.

Is this docker with self update ?

**Comment by ymurawski** [comment] 2022-04-11 17:31
> > Is this docker with self update ?
> 
> It would require pulling the latest image on the host and running the `docker run` on the host. I'm sure we could automate that with some shell script that you would need to run when a new update is found.

Ok i will try it today. Do you know wich command would pull the latest updates ?

**Comment by ymurawski** [comment] 2022-04-11 18:22
so the docker runs with version 1.8.0

just need a script which checks and installs if there is an update ?!

Thanks

**Comment by inverse** [comment] 2022-04-12 12:58
> Ok i will try it today. Do you know wich command would pull the latest updates ?

```bash
docker pull ghcr.io/tasmoadmin/tasmoadmin:latest
```

You would just need to run this when there is a new version...

**Comment by inverse** [comment] 2022-09-04 21:21
Closing as solved - feel free to open a new issue if you think there is a problem

**Closed by inverse** 2022-09-04 21:21 UTC
